### PR TITLE
Migrate to prop-types package.

### PR DESCRIPTION
**Pull request by peacechen**
Use prop-types package (React.PropTypes has been deprecated).
Conditionally use ViewPropTypes (View.propTypes has been deprecated).
See  #54

### CODE REVIEW

**Comment by williamoliveira** [comment]
Could this be merged please? That console warning is annoying

**Comment by johngoren** [comment]
Another request for a nice merge...for me this issue went beyond a console warning into a red screen.

**Comment by peacechen** [comment]
Until this PR is merged, you can point to my fork in your package.json:
`
"react-native-autocomplete-input": "https://github.com/peacechen/react-native-autocomplete-input"
`

**Comment by l-urence** [comment]
Changes are merged to master and release to npm. Thx @peacechen!

**Pull request closed without merging**
