### PR TITLE
scrollview for items

### PR DESCRIPTION
**Pull request by kesha-antonov**
If you have a lot of items you can set
`listStyle={height: 100}` and scroll them

### CODE REVIEW

**Comment by l-urence** [comment]
Sweet! Thanks again for working on this.

**Comment by kesha-antonov** [comment]
Thanks!
But I found an issue with this.
When you click on ScrollView (any item) - TextInput will lose focus and hence hide rendered items and then you can't detect what item have been clicked. I'm working on it.
So probably you should rollback for now

**Comment by l-urence** [comment]
I think the issue you described is going to be fixed with `keyboardShouldPersistTaps={true}`. Right now I replace the for loop which renders the items with a `ListView` and I will add the `keyboardShouldPersistTaps` prop too.

**Comment by kesha-antonov** [comment]
Yeah! Just did the same :)

**Comment by l-urence** [comment]
It's all in the repo and published on npm

**Comment by kesha-antonov** [comment]
Thanks man!

**Pull request closed without merging**
